// CSS
import "./globals.css";

// Font
import { Raleway } from "@next/font/google";

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
});

// Metadata
export const metadata = {
  title: "Blop - A Social Network",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className={`${raleway.variable} font-sans`} lang="en">
      <body>{children}</body>
    </html>
  );
}
